# This is a basic workflow to help you get started with Actions

name: deploy-web

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

#      - name: 🏗 Setup Node
#        uses: actions/setup-node@v2
#        with:
#           node-version: 16.x
##           cache: yarn
#
#      - name: Expo GitHub Action
#        uses: expo/expo-github-action@7.2.0
#        with:
#          expo-version: latest
#
#      - name: 📦 Install dependencies
#        run: yarn install
#
#      - name: Build web
#        run: "yarn run buildWeb"

      - name: Vercel Action
        uses: amondnet/vercel-action@v20.0.1
        with:
#          github-token: ${{ secrets.DEPLOY_TOKEN }} #Optional
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          vercel-org-id: ${{ secrets.ORG_ID}}  #Required
          vercel-project-id: ${{ secrets.PROJECT_ID}} #Required
          alias-domains: waimai-sable.vercel.app


